/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekt;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Random;

/**
 *
 * @author lukaszgolojuch
 */
public class gra_single extends javax.swing.JFrame {

    /**
     * Creates new form gra_single
     */
    public gra_single() {
        initComponents();
        String s2 = String.valueOf(Projekt.bank1);
        jTextField3.setText("$"+s2);
        int l;
        l=0;
        String s = null;
        int m;
        int i;
        BufferedReader file1;
        try {
            file1 = new BufferedReader(new FileReader("resources/slowa.txt"));
            Scanner wej= new Scanner (file1);
                 while(wej.hasNextLine()){
                 s=wej.nextLine();
                 l=l+1;
        }} catch (FileNotFoundException ex) {
            Logger.getLogger(gra_single.class.getName()).log(Level.SEVERE, null, ex);
        }

        Random r = new Random();
        int a = r.nextInt(l);
        try {
            file1 = new BufferedReader(new FileReader("resources/slowa.txt"));
            Scanner wej= new Scanner (file1);
                 for(i=0; i<a; i++)
        {
            s=wej.nextLine();
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(gra_single.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Projekt.haslo=s;
        
        
        int d=Projekt.haslo.length();
        String gwiazdki="";
        for(i=0; i<d; i++)
        {
            gwiazdki=gwiazdki+"*";
       }
        jTextField1.setText(gwiazdki);
        jTextField1.setEditable(false);
        jTextField3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText(" ");

        jButton1.setText("Sprawdź");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kup literę");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Znam hasło!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String pomocniczy;
       String pomocniczy2=jTextField1.getText();
       char[] slowo = pomocniczy2.toCharArray();
       int p=0;
       String haslopomoc="";
       int l=Projekt.haslo.length();        //długość hasłą
       pomocniczy=jTextField2.getText();
        if(pomocniczy.length()==0)
        {
             JOptionPane.showMessageDialog(this, "Nie podano litery");
             //jTextField1.setText(pomocniczy2);
        }
        if(pomocniczy.length()>1)
        {
            JOptionPane.showMessageDialog(this, "Podano za dużo liter");
             //jTextField1.setText(pomocniczy2);
        }
        if(pomocniczy.length()==1)
        {
        String password=Projekt.haslo;
        char litera2=pomocniczy.charAt(0);
        boolean wyst;  //czy nasza litera wystapila w hasle
        for(int i=0; i<l; i++)
        {
        char litera=password.charAt(i);
        
        if(litera==litera2)
        {
            p++;
            haslopomoc=haslopomoc+litera2;
        }
        else
        {
            haslopomoc=haslopomoc+slowo[i];  //dodajemy to co już odkryte a nie zawsze gwiazdki
        }
        }
        jTextField1.setText(haslopomoc);
        jTextField2.setText("");
        }
         
        if (p==0)
        {
        Projekt.bank1=Projekt.bank1-100;
        String s2 = String.valueOf(Projekt.bank1);
        jTextField3.setText("$"+s2);
        if(Projekt.bank1<=0)
        {
        JOptionPane.showMessageDialog(this, "Bankrut");
         new koniec_single().setVisible(true);
           this.setVisible(false); 
        }
        }
        
        if(haslopomoc == null ? Projekt.haslo == null : haslopomoc.equals(Projekt.haslo))
        {
        Projekt.bank1=Projekt.bank1+50;
        String s2 = String.valueOf(Projekt.bank1);
        jTextField3.setText("$"+s2);
            JOptionPane.showMessageDialog(this, "Brawo "+Projekt.imie1+"!!!"+"    Masz na koncie $"+Projekt.bank1);
            this.setVisible(false); 
            new gra_single().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String zgaduj;
        zgaduj=JOptionPane.showInputDialog("Podaj słowo:","Wpisz tutaj");
         
        if("Wpisz tutaj".equals(zgaduj)||"".equals(zgaduj)||zgaduj==null)
        {
        JOptionPane.showMessageDialog(this, "Nie podano słowa");
        }
        else
        {
        if(zgaduj == null ? Projekt.haslo == null : zgaduj.equals(Projekt.haslo))
        {
        Projekt.bank1=Projekt.bank1+100;
        String s2 = String.valueOf(Projekt.bank1);
        jTextField3.setText("$"+s2);  
            JOptionPane.showMessageDialog(this, "Brawo "+Projekt.imie1+"!!!"+"    Masz na koncie $"+Projekt.bank1);
           Projekt.gracz++;
           this.setVisible(false); 
            new gra_single().setVisible(true);
        }
        else
        {
        Projekt.bank1=Projekt.bank1-500;
        String s2 = String.valueOf(Projekt.bank1);
        jTextField3.setText("$"+s2);
        JOptionPane.showMessageDialog(this, "Błędne słowo");
        }
        if(Projekt.bank1<=0)
        {
        JOptionPane.showMessageDialog(this, "Bankrut");
         new koniec_single().setVisible(true);
           this.setVisible(false); 
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Projekt.bank1=Projekt.bank1-200;
        jTextField3.setText("$"+Projekt.bank1);    //dodałem to bo nie pokazywało ale pewnie trzeba gdzieś jeszcze
        if(Projekt.bank1<=0)
        {
        JOptionPane.showMessageDialog(this, "Bankrut");
         new koniec_single().setVisible(true);
           this.setVisible(false); 
        }
        int d=jTextField1.getText().length();
        String wyraz=jTextField1.getText();
        String pomocniczy="";
        char litera;
        char litera2;
        int i, j;
        j=0;
        i=-1;
        while(j==0)
        {
            i=i+1;
            if(wyraz.charAt(i)=='*')
            {
                j=1;
            }
        }
        litera=Projekt.haslo.charAt(i);
        for(i=0; i<d; i++)
        {
            litera2=Projekt.haslo.charAt(i);
            if(litera2==litera)
            {
                pomocniczy=pomocniczy+litera;
            }
            else
            {
                pomocniczy=pomocniczy+wyraz.charAt(i);
                
            }
        }
        jTextField1.setText(pomocniczy);
        if(pomocniczy == null ? Projekt.haslo == null : pomocniczy.equals(Projekt.haslo))
        {
            Projekt.bank1=Projekt.bank1+50;
            jTextField3.setText("$"+Projekt.bank1);    //i to też bo trochę bug jak co innego na okienku i co innego tu 
            JOptionPane.showMessageDialog(this, "Brawo "+Projekt.imie1+"!!!"+"    Masz na koncie $"+Projekt.bank1);
               Projekt.gracz++;
            this.setVisible(false); 
            new gra_single().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gra_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gra_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gra_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gra_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gra_single().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
